=== josefaidt/aws-amplify-2/packages/outputs-schema/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://amplify.aws/2024-02/outputs-schema.json",
  "title": "AWS Amplify (Gen 2) Backend Outputs",
  "description": "outputs generated by AWS Amplify (Gen 2) backends",
  "type": "object",
  "properties": {
    "_version": {
      "type": "string"
    },
    "auth": {
      "description": "Outputs generated from defineAuth",
      "type": "object",
      "properties": {
        "aws_region": {
          "$ref": "#/$defs/aws_region"
        },
        "user_pool_id": {
          "description": "Cognito User Pool ID",
          "type": "string"
        },
        "user_pool_client_id": {
          "description": "Cognito User Pool Client ID",
          "type": "string"
        },
        "identity_pool_id": {
          "description": "Cognito Identity Pool ID",
          "type": "string"
        },
        "password_policy_min_length": {
          "type": "number",
          "minimum": 1
        },
        "password_policy_characters": {
          "type": "array",
          "items": {
            "enum": [
              "REQUIRES_NUMBERS",
              "REQUIRES_LOWERCASE",
              "REQUIRES_UPPERCASE",
              "REQUIRES_SYMBOLS"
            ]
          }
        },
        "social_providers": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 0,
          "uniqueItems": true
        },
        "oauth_domain": {
          "type": "string"
        },
        "oauth_scope": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 0,
          "uniqueItems": true
        },
        "oauth_redirect_sign_in": {
          "type": "string"
        },
        "oauth_redirect_sign_out": {
          "type": "string"
        },
        "oauth_response_type": {
          "type": "string",
          "enum": ["code", "token"]
        },
        "user_signup_atributes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "user_username_attributes": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["email", "phone"]
          }
        },
        "user_verification_mechanisms": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["email", "phone"]
          }
        },
        "mfa_configuration": {
          "type": "string",
          "enum": ["NONE", "OPTIONAL", "REQUIRED"]
        },
        "mfa_methods": {
          "type": "array",
          "items": {
            "enum": ["SMS", "TOTP"]
          }
        }
      }
    },
    "data": {
      "aws_region": {
        "$ref": "#/$defs/aws_region"
      },
      "url": {
        "description": "AppSync endpoint URL",
        "type": "string"
      },
      "model_introspection": {
        "description": "generated model introspection schema for use with generateClient",
        "type": "object"
      },
      "api_key": {
        "type": "string"
      },
      "default_authorization_type": {
        "type": "string"
      },
      "authorization_types": {
        "type": "array",
        "items": {
          "type": "string",
          "enum": [
            "AMAZON_COGNITO_USER_POOLS",
            "API_KEY",
            "AWS_IAM",
            "AWS_LAMBDA",
            "OPENID_CONNECT"
          ]
        }
      }
    },
    "storage": {
      "type": "object",
      "properties": {
        "aws_region": {
          "$ref": "#/$defs/aws_region"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "custom": {
      "type": "object"
    }
  },
  "$defs": {
    "aws_region": {
      "type": "string",
      "enum": ["us-east-1", "us-east-2", "us-west-1", "us-west-2"]
    }
  }
}

=== josefaidt/aws-amplify-2/packages/outputs-schema/example.json
{
  "$schema": "./schema.json",
  "_version": "0.1.0",
  "auth": {
    "aws_region": "us-east-1",
    "identity_pool_id": "...",
    "user_pool_client_id": "...",
    "user_pool_id": "...",
    "oauth_domain": "https://cognito.com...",
    "oauth_redirect_sign_in": "http://localhost:3000/welcome",
    "oauth_redirect_sign_out": "http://localhost:3000/come-back-soon",
    "oauth_response_type": "code",
    "oauth_scope": ["profile", "..."],
    "password_policy_characters": [
      "REQUIRES_LOWERCASE",
      "REQUIRES_UPPERCASE",
      "REQUIRES_NUMBERS",
      "REQUIRES_SYMBOLS"
    ],
    "password_policy_min_length": 32,
    "social_providers": ["Google", "Midway"],
    "user_signup_atributes": ["email"],
    "user_verification_mechanisms": ["email"],
    "user_username_attributes": ["email"],
    "mfa_configuration": "OPTIONAL",
    "mfa_methods": ["SMS"]
  },
  "data": {
    "aws_region": "us-east-1",
    "url": "https://...",
    "model_introspection": {},
    "default_authorization_type": "AMAZON_COGNITO_USER_POOLS",
    "authorization_types": ["AMAZON_COGNITO_USER_POOLS", "AWS_IAM"]
  },
  "storage": {
    "aws_region": "us-east-1",
    "name": "myphotos-dev"
  },
  "custom": {
    "my_function_url": "https://..."
  }
}
