=== josefaidt/aws-amplify-2/packages/outputs-schema/v0.8/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://amplify.aws/2024-02/outputs-schema.json",
  "title": "AWS Amplify (Gen 2) Backend Outputs",
  "description": "outputs generated by AWS Amplify (Gen 2) backends",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "description": "JSON schema",
      "type": "string"
    },
    "_version": {
      "description": "Version of this schema",
      "const": "1"
    },
    "auth": {
      "description": "Outputs generated from defineAuth",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "aws_region": {
          "description": "AWS Region of Amazon Cognito resources",
          "$ref": "#/$defs/aws_region"
        },
        "user_pool_id": {
          "description": "Cognito User Pool ID",
          "type": "string"
        },
        "user_pool_client_id": {
          "description": "Cognito User Pool Client ID",
          "type": "string"
        },
        "identity_pool_id": {
          "description": "Cognito Identity Pool ID",
          "type": "string"
        },
        "password_policy": {
          "description": "Cognito User Pool password policy",
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "min_length": {
              "type": "number",
              "minimum": 1
            },
            "require_numbers": {
              "type": "boolean"
            },
            "require_lowercase": {
              "type": "boolean"
            },
            "require_uppercase": {
              "type": "boolean"
            },
            "require_symbols": {
              "type": "boolean"
            }
          }
        },
        "identity_providers": {
          "description": "Identity providers set on Cognito User Pool",
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 0,
          "uniqueItems": true
        },
        "oauth_domain": {
          "description": "Cognito Domain used for identity providers",
          "type": "string"
        },
        "oauth_scope": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 0,
          "uniqueItems": true
        },
        "oauth_redirect_sign_in": {
          "description": "URIs used to redirect after signing in using an identity provider",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "oauth_redirect_sign_out": {
          "description": "URIs used to redirect after signing out",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "oauth_response_type": {
          "type": "string",
          "enum": ["code", "token"]
        },
        "standard_attributes": {
          "description": "Cognito User Pool standard attributes",
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "address": {
              "$ref": "#/$defs/amazon_cognito_standard_attributes_config"
            },
            "birthdate": {
              "$ref": "#/$defs/amazon_cognito_standard_attributes_config"
            },
            "email": {
              "$ref": "#/$defs/amazon_cognito_standard_attributes_config"
            },
            "family_name": {
              "$ref": "#/$defs/amazon_cognito_standard_attributes_config"
            },
            "gender": {
              "$ref": "#/$defs/amazon_cognito_standard_attributes_config"
            },
            "given_name": {
              "$ref": "#/$defs/amazon_cognito_standard_attributes_config"
            },
            "locale": {
              "$ref": "#/$defs/amazon_cognito_standard_attributes_config"
            },
            "middle_name": {
              "$ref": "#/$defs/amazon_cognito_standard_attributes_config"
            },
            "name": {
              "$ref": "#/$defs/amazon_cognito_standard_attributes_config"
            },
            "nickname": {
              "$ref": "#/$defs/amazon_cognito_standard_attributes_config"
            },
            "phone_number": {
              "$ref": "#/$defs/amazon_cognito_standard_attributes_config"
            },
            "picture": {
              "$ref": "#/$defs/amazon_cognito_standard_attributes_config"
            },
            "preferred_username": {
              "$ref": "#/$defs/amazon_cognito_standard_attributes_config"
            },
            "profile": {
              "$ref": "#/$defs/amazon_cognito_standard_attributes_config"
            },
            "sub": {
              "$ref": "#/$defs/amazon_cognito_standard_attributes_config"
            },
            "updated_at": {
              "$ref": "#/$defs/amazon_cognito_standard_attributes_config"
            },
            "website": {
              "$ref": "#/$defs/amazon_cognito_standard_attributes_config"
            },
            "zoneinfo": {
              "$ref": "#/$defs/amazon_cognito_standard_attributes_config"
            }
          }
        },
        "username_attributes": {
          "description": "Cognito User Pool username attributes",
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["EMAIL", "PHONE"]
          }
        },
        "user_verification_mechanisms": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["EMAIL", "PHONE"]
          }
        },
        "unauthenticated_identities_enabled": {
          "type": "boolean",
          "default": true
        },
        "mfa_configuration": {
          "type": "string",
          "enum": ["NONE", "OPTIONAL", "REQUIRED"]
        },
        "mfa_methods": {
          "type": "array",
          "items": {
            "enum": ["SMS", "TOTP"]
          }
        }
      }
    },
    "data": {
      "description": "Outputs generated from defineData",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "aws_region": {
          "$ref": "#/$defs/aws_region"
        },
        "url": {
          "description": "AppSync endpoint URL",
          "type": "string"
        },
        "model_introspection": {
          "description": "generated model introspection schema for use with generateClient",
          "type": "object"
        },
        "api_key": {
          "type": "string"
        },
        "default_authorization_type": {
          "$ref": "#/$defs/aws_appsync_authorization_type"
        },
        "authorization_types": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/aws_appsync_authorization_type"
          }
        }
      }
    },
    "storage": {
      "type": "object",
      "description": "Outputs generated from defineStorage",
      "additionalProperties": false,
      "properties": {
        "aws_region": {
          "$ref": "#/$defs/aws_region"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "custom": {
      "description": "Outputs generated from backend.addOutput({ custom: <config> })",
      "type": "object"
    }
  },
  "$defs": {
    "aws_region": {
      "type": "string"
    },
    "amazon_cognito_standard_attributes_config": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "required": {
          "type": "boolean"
        }
      }
    },
    "aws_appsync_authorization_type": {
      "type": "string",
      "enum": [
        "AMAZON_COGNITO_USER_POOLS",
        "API_KEY",
        "AWS_IAM",
        "AWS_LAMBDA",
        "OPENID_CONNECT"
      ]
    }
  }
}

=== josefaidt/aws-amplify-2/packages/outputs-schema/v0.8/example.json
{
  "$schema": "./schema.json",
  "_version": "1",
  "auth": {
    "aws_region": "us-east-1",
    "identity_pool_id": "...",
    "user_pool_client_id": "...",
    "user_pool_id": "...",
    "oauth_domain": "https://cognito.com...",
    "oauth_redirect_sign_in": ["http://localhost:3000/welcome"],
    "oauth_redirect_sign_out": ["http://localhost:3000/come-back-soon"],
    "oauth_response_type": "code",
    "oauth_scope": ["profile", "..."],
    "password_policy": {
      "require_lowercase": true,
      "require_uppercase": true,
      "require_symbols": true,
      "require_numbers": true
    },
    "identity_providers": ["Google", "Midway"],
    "standard_attributes": {
      "email": {
        "required": true
      }
    },
    "username_attributes": ["EMAIL"],
    "user_verification_mechanisms": ["EMAIL"],
    "unauthenticated_identities_enabled": true,
    "mfa_configuration": "OPTIONAL",
    "mfa_methods": ["SMS"]
  },
  "data": {
    "aws_region": "us-east-1",
    "url": "https://...",
    "model_introspection": {},
    "default_authorization_type": "AMAZON_COGNITO_USER_POOLS",
    "authorization_types": ["AMAZON_COGNITO_USER_POOLS", "AWS_IAM"]
  },
  "storage": {
    "aws_region": "us-east-1",
    "name": "myphotos-dev"
  },
  "custom": {
    "my_function_url": "https://..."
  }
}
